# Generated by Django 5.1.2 on 2024-10-26 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_pet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='health_status',
            field=models.CharField(choices=[('vaccinated', 'Vaccinated'), ('spayed', 'Spayed'), ('neutered', 'Neutered'), ('medical_conditions', 'Medical Conditions')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='posted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
