# Generated by Django 5.1.2 on 2024-10-26 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_pet_adoption_fee_pet_color_pet_health_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
