# Generated by Django 5.1.2 on 2024-10-26 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_alter_pet_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
