# Generated by Django 5.1.2 on 2024-10-30 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_alter_pet_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
